jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'


server:
  #address: 192.168.225.65 Now local host
  port: 8081
#  error:
#    whitelabel:
#      enabled: false

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/supportportal
    url: jdbc:mysql://localhost:3306/sales
    password: admin
    username: root
  jpa:
    #show-sql: true
    show-sql: false
    hibernate:
      ddl-auto: update
      value: 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: balasilvaee@gmail.com
    password: ippszaiehlfstlxy
    protocol: smtp    
    tls: true
    properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com          
    
logging:
  file:
    name: application.log
    max-history: 1
    max-size: 10MB      
    path: logs
  pattern:
    console: "%d{dd.MM.yyyy HH:mm:ss.SSS} [%thread] %highlight([%-5level]) %-85(%green([%class{36}.%M %L]))  - %msg%n" 
    rolling-file-name: ${LOG_FILE}.%d{yyyy-MM-dd}.%i
  
 
user.profileimage.path : /USER/PROFILEIMAGE/  


   