package com.gopro.queryconstant;

public interface NotificationMessageMapQueryConstant {

	public static final String  FIND_ALL_MESSAGE_ID_BY_NOTIFICATION_ID = "select notificationMessageMapId from notificationMessageMap WHERE notificationId = :notificationId";
	
	//public static final String FIND_ALL_MESSAGE_BY_NOTIFICATION_ID = "select notmes.notificationMessageMapId,notmes.parentNotificationMessageMapId,notmes.sendFrom, usr.firstName, usr.lastName,notmes.message,notmes.notificationId,notmes.time from notificationMessageMap notmes INNER JOIN User usr on notmes.sendFrom = usr.id INNER JOIN notificationUserMap notusr on notusr.notificationMessageMapId = notmes.notificationMessageMapId WHERE (notmes.sendFrom = :logInUserId OR notusr.sendTo = :logInUserId) AND notmes.notificationId = :notificationId group by notmes.notificationMessageMapId order by notmes.time asc";
	
	//public static final String FIND_ALL_MESSAGE_BY_NOTIFICATION_ID = "select notmes.notificationMessageMapId,notmes.parentNotificationMessageMapId,notmes.sendFrom, usr.firstName, usr.lastName,notmes.message,notmes.notificationId,notmes.time from notificationMessageMap notmes INNER JOIN User usr on notmes.sendFrom = usr.id INNER JOIN notificationUserMap notusr on notusr.notificationMessageMapId = notmes.notificationMessageMapId WHERE notmes.time <= ( select max(innernotmes.time) from notificationMessageMap innernotmes INNER JOIN notificationUserMap innernotusr on innernotusr.notificationMessageMapId = innernotmes.notificationMessageMapId WHERE (innernotmes.sendFrom = :logInUserId OR innernotusr.sendTo = :logInUserId) AND innernotmes.notificationId = :notificationId ) AND (notmes.sendFrom = :logInUserId OR notusr.sendTo = :logInUserId) AND notmes.notificationId = :notificationId group by notmes.notificationMessageMapId order by notmes.time asc";
	
	//public static final String FIND_ALL_MESSAGE_BY_NOTIFICATION_ID = "select notmes.notificationMessageMapId,notmes.parentNotificationMessageMapId,notmes.sendFrom, usr.firstName, usr.lastName,notmes.message,notmes.notificationId,notmes.time from notificationMessageMap notmes INNER JOIN User usr on notmes.sendFrom = usr.id INNER JOIN notificationUserMap notusr on notusr.notificationMessageMapId = notmes.notificationMessageMapId WHERE notmes.time <= ( select max(innernotmes.time) from notificationMessageMap innernotmes INNER JOIN notificationUserMap innernotusr on innernotusr.notificationMessageMapId = innernotmes.notificationMessageMapId WHERE (innernotmes.sendFrom = :logInUserId OR innernotusr.sendTo = :logInUserId) AND innernotmes.notificationId = :notificationId ) AND notmes.notificationId = :notificationId group by notmes.notificationMessageMapId order by notmes.time asc";
	
	public static final String FIND_ALL_MESSAGE_BY_NOTIFICATION_ID  = "SELECT notmes.notificationMessageMapId, notmes.parentNotificationMessageMapId, notmes.sendFrom, usr.firstName, usr.lastName, notmes.message, notmes.notificationId, notmes.time FROM   notificationMessageMap notmes INNER JOIN USER usr ON notmes.sendFrom = usr.id INNER JOIN notificationUserMap notusr ON notusr.notificationMessageMapId = notmes.notificationMessageMapId WHERE  notusr.sendTo = :logInUserId AND notusr.isdeleted <> 1 AND notmes.notificationId = :notificationId GROUP  BY notmes.notificationMessageMapId ORDER  BY notmes.time ASC";
	
	public static final String FIND_LAST_MESSAGE_BY_NOTIFICATION_ID = "select notmes.notificationMessageMapId,notmes.sendFrom, usr.firstName, usr.lastName,notmes.message,notmes.notificationId,notmes.time from notificationMessageMap notmes INNER JOIN User usr on notmes.sendFrom = usr.id INNER JOIN notificationUserMap notusr on (notusr.notificationMessageMapId = notmes.notificationMessageMapId AND notusr.isdeleted <> 1) WHERE (notmes.sendFrom = :logInUserId OR notusr.sendTo = :logInUserId) AND notmes.notificationId = :notificationId order by notmes.time desc LIMIT 1";

}
